name: "build"

on: ["pull_request", "push"]

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.3.4"
      - name: "Setup JDK 16"
        uses: "actions/setup-java@v2.2.0"
        with:
          distribution: "temurin"
          java-version: "16"
      - name: "Grab versions"
        uses: "HardNorth/github-version-generate@v1.1.1"
        with:
          version-source: "file"
          version-file: "gradle.properties"
          version-file-extraction-pattern: "(?<=version=).+"
      - name: "Clean Build"
        run: "./gradlew clean build"
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PlotHider-${{ env.CURRENT_VERSION }}
          path: build/libs/PlotHider-${{ env.CURRENT_VERSION }}.jar
