name: draft release

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on : ubuntu-latest
    steps :
      - uses : release-drafter/release-drafter@v5.17.6
        env :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
